apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
  namespace: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaweb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: javapod
      namespace: flipkart
      labels:
        app: javaweb
    spec:
      containers:
      imagePullSecrets:
      - name: dockerreposecret
        image: 172.31.11.149:8084/javawebapp:6
        name: javacontainer
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  name: javaservice
  namespace: flipkart
spec:
  type: NodePort
  selector:
    app: javaweb
  ports:
  - port: 80
    targetPort: 9090
